// sweng/app/log/page.tsx
"use client"
import { supabase } from "@/db/supa";
import { useRouter } from "next/navigation";    
import Link from "next/link";            

export default function LogPage() {
  
    const router = useRouter();

    const goHome = () => {
        router.push('/'); 
    };


    return (

        <main className = "flex flex-col min-h-screen bg-[#f9fdff] text-black">

            {/* Header */}
            <div className = "h-[0.75in] border-b-[5px] border-b-[#c15555]">

                <div className = "p-[0.125in] gap-[0.25in] flex flex-row items-center">

                    <img 
                        className = "h-[0.5in]" 
                        src = "/images/logo.png" 
                    />

                    <div className = "text-[30px] text-[#8a2d2d] hover:underline">
                        <h1>Red Bank Foundation</h1>
                    </div>

                </div>

            </div>

            {/* Main Content */}
            <div className = "h-[80%] bg-[#c15555] flex flex-row">

                {/* Left Panel */}
                <div className = "h-full w-[1.3in] bg-[#c15555] flex flex-col pt-[0.5in] gap-[0.25] items-center">

                    {/* Buttons */}
                    <div className = "flex flex-col gap-6 mt-8">

                        {/* Scanner Button */}
                        <Link
                            href = "/scanner"
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >
                            <img src = "/images/scanner.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform"/>

                            <p className = "mt-2 text-sm font-bold text-black-700">Scan QR</p>

                        </Link>

                        {/* Register Button */}
                        <Link 
                            href = "/register" 
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >

                            <img src = "/images/registration.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform" />
                            
                            <p className = "mt-2 text-sm font-bold text-black-700">Register</p>

                        </Link>

                        {/* Log Button */}
                        <Link 
                            href = "/log" 
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >

                            <img src = "/images/log.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform" />
                            
                            <p className = "mt-2 text-sm font-bold text-black-700">Log</p>

                        </Link>

                    </div>

                </div>

                {/* Main Panel */}
                <div className = "h-full w-[15in] bg-[#f9fdff] p-[0.5in] flex flex-col gap-[0.5in]">

                    <h1 className = "inline bg-[#c15555] text-[56px] text-[#f9fdff] p-[0.25in]">Activity Log</h1>

                    <div className = "flex flex-col">

                        <div className = "flex flex-row py-[0.125in] px-[0.25in] text-[30px] font-bold border-t-[7.5px] border-b-[7.5px] border-[#8a2d2d]">
                            
                            <div className = "w-[4in]">
                                <p>Date and Time &#8593;</p>
                            </div>
                            
                            <div className = "w-[3in]">
                                <p>User</p>
                            </div>

                            <div className="w-[3in]">
                                <p>User Type</p>
                            </div>
                            
                            <div className="flex-1">
                                <p>Activity</p>
                            </div>
                        </div>

                        <div className = "flex flex-row py-[0.125in] px-[0.25in] text-[24px] border-b-[7.5px] border-[#8a2d2d]">

                            <div className = "w-[4in]">
                                <p>2026-06-03 | 06:31:12</p>
                            </div>

                            <div className = "w-[3in]">
                                <p>Jason Doe</p>
                            </div>

                            <div className = "w-[3in]">
                                <p>Admin</p>
                            </div>

                            <div className = "flex-1">
                                <p>Register donor (John Doe)</p>
                            </div>
                        </div>
                        
                        <div className = "flex flex-row py-[0.125in] px-[0.25in] text-[24px] border-b-[7.5px] border-[#8a2d2d]">
                            
                            <div className="w-[4in]">
                                <p>2026-06-03 | 06:32:10</p>
                            </div>

                            <div className="w-[3in]">
                                <p>John Doe</p>
                            </div>

                            <div className="w-[3in]">
                                <p>Donor</p>
                            </div>

                            <div className="flex-1">
                                <p>Check in</p>
                            </div>
                        </div>

                        <div className="flex flex-row py-[0.125in] px-[0.25in] text-[24px] border-b-[7.5px] border-[#8a2d2d]">
                            <div className="w-[4in]">
                                <p>2026-06-03 | 06:34:27</p>
                            </div>

                            <div className="w-[3in]">
                                <p>John Doe</p>
                            </div>

                            <div className="w-[3in]">
                                <p>Donor</p>
                            </div>

                            <div className="flex-1">
                                <p>Claim sponsor perk (004)</p>
                            </div>
                        </div>

                        <div className="flex flex-row py-[0.125in] px-[0.25in] text-[24px] border-b-[7.5px] border-[#8a2d2d]">
                            <div className="w-[4in]">
                                <p>2026-06-03 | 07:01:45</p>
                            </div>

                            <div className="w-[3in]">
                                <p>Jane Doe</p>
                            </div>

                            <div className="w-[3in]">
                                <p>Internal Staff</p>
                            </div>

                            <div className="flex-1">
                                <p>Update donor data (John Doe)</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div className = "flex-1 bg-[#c15555]"></div>

            </div>

            <div className = "border-t-[5px] border-[#c15555] bg-[#8a2d2d] flex-1">

                <div className = "p-[0.125in] items-center text-[#f9fdff]">
                
                </div>
            </div>

        </main>

    );
}

// initial-svelte/src/routes/log/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";

    function goHome() {
        goto('/landing');
    }
</script>

<svelte:head>
    <title>Activity Log</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</svelte:head>

<div class="log-page">
    <div class="banner">
        <div class="banner-content">
            <img src="/images/logo.png" alt="Red Bank Foundation logo" />
            <div class="webname">
                <button class="home-btn" onclick={goHome}><h1 id="webname">Red Bank Foundation</h1></button>
            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="navi">
            <div class="menu scan">
                <a href="/scanner"><img src="/images/scanner.png" alt="Scan QR icon" /></a>
                <p>Scan QR</p>
            </div>

            <div class="menu regis">
                <a href="/registration"><img src="/images/registration.png" alt="Register icon" /></a>
                <p>Register</p>
            </div>

            <div class="menu log">
                <img src="/images/log.png" alt="Activity Log icon" />
                <p>Log</p>
            </div>
        </div>

        <div class="main-panel">
            <h1>Activity Log</h1>

            <div class="log-field">
                <div class="header-row">
                    <div class="col-date">
                        <p>Date and Time &#8593;</p>
                    </div>
                    
                    <div class="col-user">
                        <p>User</p>
                    </div>

                    <div class="col-type">
                        <p>User Type</p>
                    </div>
                    
                    <div class="col-act">
                        <p>Activity</p>
                    </div>
                </div>

                <div class="log-row">
                    <div class="col-date">
                        <p>2026-06-03 | 06:31:12</p>
                    </div>

                    <div class="col-user">
                        <p>Jason Doe</p>
                    </div>

                    <div class="col-type">
                        <p>Admin</p>
                    </div>

                    <div class="col-act">
                        <p>Register donor (John Doe)</p>
                    </div>
                </div>
                
                <div class="log-row">
                    <div class="col-date">
                        <p>2026-06-03 | 06:32:10</p>
                    </div>

                    <div class="col-user">
                        <p>John Doe</p>
                    </div>

                    <div class="col-type">
                        <p>Donor</p>
                    </div>

                    <div class="col-act">
                        <p>Check in</p>
                    </div>
                </div>

                <div class="log-row">
                    <div class="col-date">
                        <p>2026-06-03 | 06:34:27</p>
                    </div>

                    <div class="col-user">
                        <p>John Doe</p>
                    </div>

                    <div class="col-type">
                        <p>Donor</p>
                    </div>

                    <div class="col-act">
                        <p>Claim sponsor perk (004)</p>
                    </div>
                </div>

                <div class="log-row">
                    <div class="col-date">
                        <p>2026-06-03 | 07:01:45</p>
                    </div>

                    <div class="col-user">
                        <p>Jane Doe</p>
                    </div>

                    <div class="col-type">
                        <p>Internal Staff</p>
                    </div>

                    <div class="col-act">
                        <p>Update donor data (John Doe)</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="right-panel"></div>
    </div>

    <div class="footer">
        <div class="footer-content">
        
        </div>
    </div>
</div>

<style>
    :global(*) {
        margin: 0;
        padding: 0;
    }

    :global(body) {
        color: black;
        background-color: #f9fdff;
        min-height: 100vh;
        display: flex;
        flex-direction: column;
    }

    .log-page {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
    }

    .banner {
        height: 0.75in;
        border-bottom: 5px solid #c15555;
    }

    .banner-content {
      padding: 0.125in;
      gap: 0.25in;
      display: flex;
      flex-direction: row;
      align-items: center;
    }

    .banner-content img {
      height: 0.5in;
    }

    .home-btn {
        border: none;
        background: none;
        padding: 0;
        font: inherit;
    }

    .webname h1 {
      font-size: 30px;
      color: #8a2d2d;
    }

    .webname h1:hover {
      text-decoration: underline;
    }

    .main-content {
      flex: 1;
      background-color: #c15555;
      display: flex;
      flex-direction: row;
    }

    .navi {
      width: 1in;
      background-color: #c15555;

      display: flex;
      flex-direction: column;
      padding-top: 0.5in;
      gap: 0.25in;
      align-items: center;
    }

    .menu img {
      height: 0.5in;
    }

    .menu p {
      margin-top: 5px;
    }

    .menu:hover {
      transform: scale(1.125);
    }

    .main-panel {
        width: 15in;
        background-color: #f9fdff;
        padding: 0.5in;

        display: flex;
        flex-direction: column;
        gap: 0.5in;
    }

    .main-panel h1 {
      display: inline;
      background-color: #c15555;
      font-size: 56px;
      color: #f9fdff;
      padding: 0.25in;
    }

    .log-field {
      display: flex;
      flex-direction: column;
    }

    .header-row {
      display: flex;
      flex-direction: row;
      padding-top: 0.125in;
      padding-bottom: 0.125in;
      padding-left: 0.25in;
      padding-right: 0.25in;
      font-size: 30px;
      font-weight: bold;
      border-top: 7.5px solid #8a2d2d;
      border-bottom: 7.5px solid #8a2d2d;
    }

    .col-date {
      width: 4in;
    }

    .col-user, .col-type {
      width: 3in;
    }

    .col-act {
      flex: 1;
    }

    .log-row {
      display: flex;
      flex-direction: row;
      padding-top: 0.125in;
      padding-bottom: 0.125in;
      padding-left: 0.25in;
      padding-right: 0.25in;
      font-size: 24px;
      border-bottom: 5px solid #8a2d2d;
    }

    .right-panel {
      flex: 1;
      background-color: #c15555;
    }

    .footer {
        height: 1in;
        border-top: 5px solid #c15555;
        background-color: #8a2d2d;
    }

    .footer-content {
      padding: 0.125in;
      text-align: center;
      color: #f9fdff;
    }
</style>
