// sweng/app/landing/page.tsx
"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

import Header from "@/components/HeaderLanding";

type LandingEvent = {
    id: string;
    title: string;
    details: string;
    image: string;
    copyright?: string;
};

const events: LandingEvent[] = [
    {
        id: "1",
        title: "Event 1",
        details:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis metus. Suspendisse ac pretium dui.",
        image: "/images/event.png",
        copyright: "copyright for event 1",
    },
    {
        id: "2",
        title: "Event 2",
        details:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis metus. Suspendisse ac pretium dui.",
        image: "/images/event.png",
        copyright: "copyright for event 2",
    },
    {
        id: "3",
        title: "Event 3",
        details:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis metus. Suspendisse ac pretium dui.",
        image: "/images/event.png",
        copyright: "copyright for event 3",
    },
];

export default function Home() {
    const router = useRouter();

    const [currentIndex, setCurrentIndex] = useState(0);

    const currentEvent = events[currentIndex];

    const handleLogin = () => {
        const view = prompt("Type 1 for OA/Registration, 2 for MP/Nurse, 3 for Lab, 4 for Recovery, 5 for RBD, 6 for SA.");

        if (view === "1") {
            router.push("/oa/events");
        } else if (view === "2") {
            router.push("/mp/events");
        } else if (view === "5") {
            router.push("/rbd/analytics");
        } else if (view === "6") {
            router.push("/sa/list");
        }
    };

    const goToPrevious = () => {
        if (currentIndex === 0) {
            setCurrentIndex(events.length - 1);
        } else {
            setCurrentIndex(currentIndex - 1);
        }
    };

    const goToNext = () => {
        if (currentIndex === events.length - 1) {
            setCurrentIndex(0);
        } else {
            setCurrentIndex(currentIndex + 1);
        }
    };

    const getIndicatorClass = (index: number) => {
        let className =
            "h-[14px] w-[14px] rounded-full border-2 border-white cursor-pointer transition ";

        if (currentIndex === index) {
            className += "bg-white";
        } else {
            className += "bg-transparent";
        }

        return className;
    };

    useEffect(() => {
        const interval = setInterval(() => {
            setCurrentIndex((prevIndex) => {
                if (prevIndex === events.length - 1) {
                    return 0;
                } else {
                    return prevIndex + 1;
                }
            });
        }, 5000);

        return () => clearInterval(interval);
    }, []);

    return (
        <main className="flex flex-col min-h-screen bg-[#f9fdff] text-black">
            <Header />

            <div className="flex-1 flex flex-row">
                {/* Left Panel */}
                <div className="w-[5in] shrink-0 bg-[#f9fdff] p-[0.5in] flex flex-col gap-[0.5in] justify-center">
                    <h1 className="text-[42px] font-['Montserrat'] font-semibold text-[#1b4054]">
                        Welcome!
                    </h1>

                    <div className="text-[21px] flex flex-col">
                        <label className="mb-[5px]" htmlFor="uname">
                            Username:
                        </label>

                        <input
                            id="uname"
                            type="text"
                            className="w-full mb-[15px] border-2 border-gray-300 rounded-md focus:border-[#1b4054] pl-[10px] pr-[10px] outline-none"
                        />

                        <label className="mb-[5px]" htmlFor="pass">
                            Password:
                        </label>

                        <input
                            id="pass"
                            type="password"
                            className="w-full border-2 border-gray-300 rounded-md focus:border-[#1b4054] pl-[10px] pr-[10px] outline-none"
                        />

                        <div className="text-[12px] text-[#1b4054] w-full text-end">
                            <p className="inline hover:underline cursor-pointer text-[#1b4054]">
                                Forgot password?
                            </p>
                        </div>
                    </div>

                    <div className="flex flex-row gap-[0.25in] ml-auto">
                        <button
                            className="w-[1in] bg-[#1b4054] text-[#f9fdff] p-[5px] rounded-[10px] text-center cursor-pointer hover:underline"
                            onClick={handleLogin}
                        >
                            Log in
                        </button>

                        <button className="w-[1in] bg-[#f9fdff] text-[#1b4054] p-[5px] rounded-[10px] text-center border-2 border-[#1b4054] cursor-pointer hover:underline">
                            Sign up
                        </button>
                    </div>
                </div>

                {/* Main Panel */}
                <div className="flex-1">
                    <div className="relative w-full h-full min-h-[500px] overflow-hidden bg-gray-200">
                        {/* Background Image */}
                        <img
                            src={currentEvent.image}
                            alt={currentEvent.title}
                            className="absolute inset-0 w-full h-full object-cover transition-all duration-500"
                        />

                        {/* Dark Overlay */}
                        <div className="absolute inset-0 bg-black/55"></div>

                        {/* Event Text */}
                        <div className="absolute right-[0.8in] bottom-[1.1in] z-20 max-w-[5in] text-white text-center">
                            <h2 className="text-[72px] leading-none font-bold font-['Montserrat'] drop-shadow-lg">
                                {currentEvent.title}
                            </h2>

                            <p className="mt-[0.25in] text-[22px] leading-snug drop-shadow-md">
                                {currentEvent.details}
                            </p>
                        </div>

                        {/* Previous Button */}
                        <button
                            type="button"
                            onClick={goToPrevious}
                            className="absolute left-[0.35in] top-1/2 z-30 -translate-y-1/2 text-white text-[52px] cursor-pointer hover:scale-110 transition-transform"
                        >
                            ‹
                        </button>

                        {/* Next Button */}
                        <button
                            type="button"
                            onClick={goToNext}
                            className="absolute right-[0.35in] top-1/2 z-30 -translate-y-1/2 text-white text-[52px] cursor-pointer hover:scale-110 transition-transform"
                        >
                            ›
                        </button>

                        {/* Indicators */}
                        <div className="absolute bottom-[0.55in] left-1/2 z-30 flex -translate-x-1/2 gap-[8px]">
                            {events.map((event, index) => (
                                <button
                                    key={event.id}
                                    type="button"
                                    onClick={() => setCurrentIndex(index)}
                                    className={getIndicatorClass(index)}
                                ></button>
                            ))}
                        </div>

                        {/* Copyright Placeholder */}
                        <p className="absolute bottom-[0.25in] left-1/2 z-30 -translate-x-1/2 text-white text-[12px]">
                            {currentEvent.copyright}
                        </p>
                    </div>
                </div>
            </div>
        </main>
    );
}

// initial-svelte/src/routes/landing/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';

    function goToView() {
        const view = prompt("Type 1 for admin, 2 for int. staff, 3 for RB director.");

        if (view === '1') { goto('/log'); }
        else if (view === '2') { goto('/search'); }
        else { goto('/analytics'); }
    }
</script>

<svelte:head>
  <title>Landing Page</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</svelte:head>

<div class="landing-page">
    <div class="banner">
        <div class="banner-content">
            <img src="/images/logo.png" alt="Red Bank Foundation Logo" />
            <div class="webname">
                <h1>Red Bank Foundation</h1>
            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="margin"></div>

        <div class="left-panel">
            <h1>Welcome!</h1>

            <div class="login-field">
                <label for="uname">Username:</label>
                <input type="text" class="uname">
                <label for="pass">Password:</label>
                <input type="password" class="pass">

                <div class="forgot-pass">
                    <p>Forgot password?</p>
                </div>
            </div>

            <div class="button-field">
                <button class="btn login" onclick={goToView}>Log in</button>
                <button class="btn signup">Sign up &#8594;</button>
            </div>
        </div>

        <div class="main-panel">
            <div class="event-field">
                <div class="header">
                    <h1 class="headline">A small act, 
                        <br>
                        a lifesaving impact.
                    </h1>
                </div>

                <div class="event-list">
                    <div class="event">
                        <div class="event-img">
                            <img src="/images/event.png" alt="event placeholder" />
                        </div>
                        
                        <div class="event-details">
                            <h3>Event title</h3>
                            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Learn more."</p>
                        </div>
                    </div>

                    <div class="event">
                        <div class="event-img">
                            <img src="/images/event.png" alt="event placeholder" />
                        </div>
                        
                        <div class="event-details">
                            <h3>Event title</h3>
                            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Learn more."</p>
                        </div>
                    </div>
                    
                </div>

                <div class="carousel">
                    <img src="/images/carousel.png" alt="fake carousel indicators" />
                </div>
            </div>

            <div class="image-field">
                <img src="/images/blood.png" alt="blood bag" />
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="footer-content">
            <p>additional text info like copyright etc</p>
        </div>
    </div>
</div>

<style>
    :global(*) {
      margin: 0;
      padding: 0;
    }

    :global(body) {
        color: black;
        background-color: #f9fdff;
        min-height: 100vh;
        display: flex;
        flex-direction: column;
    }

    .landing-page {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
    }

    .banner {
        height: 0.75in;
        border-bottom: 5px solid #c15555;
    }

    .banner-content {
        padding: 0.125in;
        gap: 0.25in;
        display: flex;
        flex-direction: row;
        align-items: center;
    }

    .banner-content img {
        height: 0.5in;
    }

    .webname h1 {
        font-size: 30;
        color: #8a2d2d;
    }

    .webname h1:hover {
        text-decoration: underline;
    }

    .main-content {
        flex: 1;
        background-color: #c15555;
        display: flex;
        flex-direction: row;
    }

    .margin {
        height: 100%;
        width: 1in;
        background-color: #c15555;
    }

    .left-panel {
        height: auto;
        width: 3.25in;
        background-color: #f9fdff;
        padding: 0.25in;

        display: flex;
        flex-direction: column;
        gap: 0.5in;
    }

    .left-panel h1 {
        font-size: 42px;
        font-weight: normal;
        margin-top: 0.25in;
    }

    .login-field {
        font-size: 18px;
        display: flex;
        flex-direction: column;
    }

    .login-field label {
        margin-bottom: 5px;
    }

    .login-field input {
        width: 3in;
    }

    .uname {
        margin-bottom: 15px;
    }

    .forgot-pass {
        font-size: 12px;
        color: #8a2d2d;
        width: 3in;
        text-align: end;
    }

    .forgot-pass p {
        display: inline;
    }

    .forgot-pass p:hover {
        text-decoration: underline;
    }

    .button-field {
        width: 3in;
        display: flex;
        flex-direction: row;
        gap: 0.25in;
    }

    .btn {
        width: 1in;
        background-color: #8a2d2d;
        color: #f9fdff;
        padding: 5px;
        border-radius: 10px;
    }

    .btn:hover {
        text-decoration: underline;
    }

    .main-panel {
        flex: 1;
        background-color: #c15555;
        padding: 0.75in;
        padding-right: 0.25in;
        display: flex;
        flex-direction: row;
        gap: 0.5in;
    }

    .event-field {
        width: 8.5in;
        display: flex;
        flex-direction: column;
        gap: 0.5in;
    }

    .headline {
        color: #f9fdff;
        font-size: 56px;
    }

    .event-list {
        width: 8in;
        display: flex;
        flex-direction: column;
        gap: 15px;
    }

    .event {
        height: 1in;
        padding: 0.25in;
        background-color: #f9fdff;
        display: flex;
        flex-direction: row;
        gap: 0.25in;
    }

    .event-img img {
        height: 1in;
    }

    .event-details {
        display: flex;
        flex-direction: column;
        gap: 0.125in;
    }

    .event-details h3 {
        font-weight: bold;
    }

    .event-details p {
        text-align: justify;
    }

    .carousel {
        width: 8in;
        margin-top: -0.5in;
        display: flex;
        justify-content: center;
    }

    .carousel img {
        height: 1in;
    }

    .image-field {
        width: 4in;
        overflow: hidden;
    }

    .image-field img {
        height: 100%;
        width: 100%;
        object-fit: cover;
    }

    .footer {
        height: 1in;
        border-top: 5px solid #c15555;
        background-color: #8a2d2d;
    }

    .footer-content {
        padding: 0.125in;
        text-align: center;
        color: #f9fdff;
    }
    </style>
