// initial-svelte/src/routes/scanner/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    
    function goHome() {
        goto('/landing');
    }

    function openLog() {
        alert('User verified!');
        goto('/log');
    }
</script>

<svelte:head>
    <title>Scanner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</svelte:head>

<div class="scanner-page">
    <div class="banner">
        <div class="banner-content">
            <img src="/images/logo.png" alt="Red Bank Foundation logo" />
            <div class="webname">
                <button class="home-btn" onclick={goHome}><h1 id="webname">Red Bank Foundation</h1></button>
            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="navi">
            <div class="menu scan">
                <img src="/images/scanner.png" alt="Scan QR icon" />
                <p>Scan QR</p>
            </div>

            <div class="menu regis">
                <a href="/registration"><img src="/images/registration.png" alt="Register icon" /></a>
                <p>Register</p>
            </div>

            <div class="menu log">
                <a href="/log"><img src="/images/log.png" alt="Activity Log icon" /></a>
                <p>Log</p>
            </div>
        </div>

        <div class="left-panel">
            <h1>Instructions:</h1>

            <div class="instructions">
                <div class="step">
                    <p>Open the Red Bank Foundation app.</p>
                </div>

                <div class="step">
                    <p>Go to user profile.</p>
                </div>
                
                <div class="step">
                    <p>Show user QR code to scanner.</p>
                </div>
            </div>
        </div>

        <div class="main-panel">
            <div class="scanner-field">
                <div class="header">
                    <h1 class="headline">Verify User</h1>
                </div>

                <div class="camera">
                    <button class="cam-btn" onclick={openLog}>
                        <img src="/images/camera.png" alt="Camera scanner placeholder" />
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="footer-content">
        
        </div>
    </div>
</div>

<style>
    ::global(*) {
      margin: 0;
      padding: 0;
    }

    :global(body) {
      color: black;
      background-color: #f9fdff;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }

    .scanner-page {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
    }

    .banner {
      height: 0.75in;
      border-bottom: 5px solid #c15555;
    }

    .banner-content {
      padding: 0.125in;
      gap: 0.25in;
      display: flex;
      flex-direction: row;
      align-items: center;
    }

    .banner-content img {
      height: 0.5in;
    }

    .home-btn {
        border: none;
        background: none;
        padding: 0;
        font: inherit;
    }

    .webname h1 {
      font-size: 30px;
      color: #8a2d2d;
    }

    .webname h1:hover {
      text-decoration: underline;
    }

    .main-content {
      flex: 1;
      background-color: #c15555;
      display: flex;
      flex-direction: row;
    }

    .navi {
      width: 1in;
      background-color: #c15555;

      display: flex;
      flex-direction: column;
      padding-top: 0.5in;
      gap: 0.25in;
      align-items: center;
    }

    .menu img {
      height: 0.5in;
    }

    .menu p {
      margin-top: 5px;
    }

    .menu:hover {
      transform: scale(1.125);
    }

    .left-panel {
      width: 3.25in;
      background-color: #f9fdff;
      padding: 0.25in;

      display: flex;
      flex-direction: column;
      gap: 0.5in;
    }

    .left-panel h1 {
      font-size: 42px;
      font-weight: normal;
      margin-top: 0.25in;
    }

    .instructions {
      font-size: 21px;
      display: flex;
      flex-direction: column;
    }

    .step {
      height: 0.75in;
      display: flex;
      align-items: center;
      border-bottom: 5px solid #8a2d2d;
    }

    .main-panel {
      flex: 1;
      background-color: #c15555;
      padding: 0.5in;
      margin-left: 0.25in;
      display: flex;
      flex-direction: row;
      gap: 0.5in;
    }

    .scanner-field {
      width: 10in;
      display: flex;
      flex-direction: column;
      gap: 0.25in;
    }

    .headline {
      color: #f9fdff;
      font-size: 56px;
    }

    .cam-btn {
        border: none;
        background: none;
        padding: 0;
    }

    .camera img {
        height: 5.5in;
    }

    .footer {
        height: 1in;
        border-top: 5px solid #c15555;
        background-color: #8a2d2d;
    }

    .footer-content {
      padding: 0.125in;
      text-align: center;
      color: #f9fdff;
    }
</style>

// sweng/app/scanner/page.tsx
"use client"
import { supabase } from "@/db/supa";
import { useRouter } from "next/navigation";    
import Link from "next/link";            

import Header from "@/components/Header";

export default function ScannerPage() {
  
    const router = useRouter();

    const goHome = () => {
        router.push('/'); 
    };

    const verifyDonor = () => {
        alert("Donor verified!");
        router.push('/log'); 
    };

    return (

        <main className = "flex flex-col min-h-screen bg-[#f9fdff] text-black">

            {/* Header */}
            <Header/>

            {/* Main Content */}
            <div className = "h-[80%] bg-[#c15555] flex flex-row">

                {/* Navigation Panel */}
                <div className = "h-full w-[1.3in] bg-[#c15555] flex flex-col pt-[0.5in] gap-[0.25] items-center">

                    {/* Buttons */}
                    <div className = "flex flex-col gap-6 mt-8">

                        {/* Scanner Button */}
                        <Link
                            href = "/scanner"
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >
                            <img src = "/images/scanner.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform"/>

                            <p className = "mt-2 text-sm font-bold text-black">Scan QR</p>

                        </Link>

                        {/* Register Button */}
                        <Link 
                            href = "/register" 
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >

                            <img src = "/images/registration.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform" />
                            
                            <p className = "mt-2 text-sm font-bold text-black">Register</p>

                        </Link>

                        {/* Log Button */}
                        <Link 
                            href = "/log" 
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >

                            <img src = "/images/log.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform" />
                            
                            <p className = "mt-2 text-sm font-bold text-black">Log</p>

                        </Link>

                    </div>

                </div>

                {/* Left Panel */}
                <div className = "w-[3.25in] bg-[#f9fdff] p-[0.25in] flex flex-col gap-[0.5in]">

                    <h1 className = "text-[42px] font-normal mt-[0.25in]">Instructions:</h1>

                    <div className = "flex flex-col text-[21px]">

                        <div className = "h-[0.75in] flex items-center border-b-[5px] border-[#8a2d2d]">
                            <p>Open the Red Bank Foundation app.</p>
                        </div>

                        <div className = "h-[0.75in] flex items-center border-b-[5px] border-[#8a2d2d]">
                            <p>Go to user profile.</p>
                        </div>
                        
                        <div className = "h-[0.75in] flex items-center border-b-[5px] border-[#8a2d2d]">
                            <p>Show QR code to scanner.</p>
                        </div>

                    </div>

                </div>

                <div className = "flex-1 bg-[#c15555] p-[0.75in] pr-[0.25in] flex flex-row gap-[0.5in]">

                    <div className = "flex flex-col w-[10in] gap-[0.25in]">

                        <div className = "header">
                            <h1 className = "text-[56px] text-[#f9fdff]">Verify User</h1>
                        </div>

                        <div className = "w-[85%]">
                            <img src = "/images/camera.png" onClick={verifyDonor}/>
                            
                        </div>
                    </div>
                </div>

            </div>

            <div className = "border-t-[5px] border-[#c15555] bg-[#8a2d2d] flex-1">

                <div className = "p-[0.125in] items-center text-[#f9fdff]">
                
                </div>
            </div>

        </main>

    );
}
