// initial-svelte/src/routes/search/+page.svelte
<script lang="ts">
    import { goto } from "$app/navigation";
    
    function goHome() {
        goto('/landing');
    }

    function openProfile() {
        goto('/profile');
    }
</script>

<svelte:head>
    <title>Donor Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</svelte:head>

<div class="search-page">
    <div class="banner">
        <div class="banner-content">
            <img src="/images/logo.png" alt="Red Bank Foundation logo" />
            <div class="webname">
                <button class="home-btn" onclick={goHome}><h1 id="webname">Red Bank Foundation</h1></button>
            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="navi">
            <div class="menu search">
                <img src="/images/search.png" alt="Search icon" />
                <p>Search</p>
            </div>

            <div class="menu events">
                <img src="/images/planner.png" alt="Event planner icon" />
                <p>Events</p>
            </div>
        </div>

        <div class="main-panel">
            <h1>Donor Search</h1>

            <div class="search-field">
                <div class="search-row">
                    <div class="search-box">
                        <img class="search-img" src="/images/search.png" alt="Search button icon" />
                        <input type="text" class="search-in" placeholder="Input donor name">
                    </div>

                    <button class="btn search">Search</button>
                </div>

                <div class="search-results">
                    <div class="res-row">
                        <button class="donor-res don-btn" onclick={openProfile}>
                            <div class="donor-img">
                                <img src="/images/user.png" alt="User icon" />
                            </div>

                            <div class="donor-details">
                                <h3>John Doe</h3>
                                <p>john_doe@gmail.com</p>
                            </div>
                        </button>

                        <div class="donor-res">
                            <div class="donor-img">
                                <img src="/images/user.png" alt="User icon" />
                            </div>

                            <div class="donor-details">
                                <h3>Janet Doe</h3>
                                <p>janet_doe@gmail.com</p>
                            </div>
                        </div>

                        <div class="donor-res">
                            <div class="donor-img">
                                <img src="/images/user.png" alt="User icon" />
                            </div>

                            <div class="donor-details">
                                <h3>Jeanne Doe</h3>
                                <p>jeanne_doe@gmail.com</p>
                            </div>
                        </div>
                    </div>

                    <div class="res-row">
                        <div class="donor-res">
                            <div class="donor-img">
                                <img src="/images/user.png" alt="User icon" />
                            </div>

                            <div class="donor-details">
                                <h3>Julian Doe</h3>
                                <p>julian_doe@gmail.com</p>
                            </div>
                        </div>

                        <div class="donor-res">
                            <div class="donor-img">
                                <img src="/images/user.png" alt="User icon" />
                            </div>

                            <div class="donor-details">
                                <h3>Jonah Doe</h3>
                                <p>jonah_doe@gmail.com</p>
                            </div>
                        </div>

                        <div class="donor-res">
                            <div class="donor-img">
                                <img src="/images/user.png" alt="User icon" />
                            </div>

                            <div class="donor-details">
                                <h3>Janice Doe</h3>
                                <p>janice_doe@gmail.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="right-panel"></div>
    </div>

    <div class="footer">
        <div class="footer-content">
        
        </div>
    </div>
</div>

<style>
    :global(*) {
        margin: 0;
        padding: 0;
    }

    :global(body) {
      color: black;
      background-color: #f9fdff;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }

    .search-page {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
    }

    .banner {
      height: 0.75in;
      border-bottom: 5px solid #c15555;
    }

    .banner-content {
      padding: 0.125in;
      gap: 0.25in;
      display: flex;
      flex-direction: row;
      align-items: center;
    }

    .banner-content img {
      height: 0.5in;
    }

    .home-btn {
        border: none;
        background: none;
        padding: 0;
        font: inherit;
    }

    .webname h1 {
      font-size: 30px;
      color: #8a2d2d;
    }

    .webname h1:hover {
      text-decoration: underline;
    }

    .main-content {
      flex: 1;
      background-color: #c15555;
      display: flex;
      flex-direction: row;
    }

    .navi {
      width: 1in;
      background-color: #c15555;

      display: flex;
      flex-direction: column;
      padding-top: 0.5in;
      gap: 0.25in;
      align-items: center;
    }

    .menu img {
      height: 0.5in;
    }

    .menu p {
      margin-top: 5px;
    }

    .menu:hover {
      transform: scale(1.125);
    }

    .main-panel {
      width: 15in;
      background-color: #f9fdff;
      padding: 0.5in;

      display: flex;
      flex-direction: column;
      gap: 0.5in;
    }

    .main-panel h1 {
      display: inline;
      background-color: #c15555;
      font-size: 56px;
      color: #f9fdff;
      padding: 0.25in;
    }

    .search-field {
      display: flex;
      flex-direction: column;
      gap: 0.5in;
    }

    .search-row {
      display: flex;
      flex-direction: row;
      gap: 0.5in;
    }

    .search-box {
      position: relative;
    }

    .search-img {
      position: absolute;
      left: 0.125in;
      top: 7.5px;
      height: 0.25in;
    }

    .search-in {
      width: 5in;
      font-size: 30px;
      padding-left: 0.5in;
    }

    .btn {
      width: 1in;
      background-color: #8a2d2d;
      color: #f9fdff;
      font-size: 21px;
      padding: 5px;
      border-radius: 10px;
    }

    .btn:hover {
      text-decoration: underline;
    }

    .search-results {
      display: flex;
      flex-direction: column;
      gap: 15px;
    }

    .res-row {
      height: 1.5in;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    }
    
    .don-btn {
        border: none;
        background: none;
        padding: 0;
        font: inherit;
        text-align: left;
    }

    .donor-res {
      height: 1.25in;
      width: 4.5in;
      background-color: #c15555;
      border-radius: 20px;
      display: flex;
      flex-direction: row;
      gap: 0.25in;
    }

    .donor-res:hover {
      transform: scale(1.0625);
    }

    .donor-img img {
      height: 1in;
      padding-left: 0.125in;
      padding-top: 0.125in;
      display: flex;
    }

    .donor-details {
      display: flex;
      flex-direction: column;
      align-self: center;
      gap: 7.5px;
    }

    .donor-details h3 {
      color: #f9fdff;
      font-size: 28px;
      font-weight: bold;
    }

    .donor-details p {
      color: #f9fdff;
      font-size: 21px;
      text-align: justify;
    }

    .right-panel {
      flex: 1;
      background-color: #c15555;
    }

    .footer {
        height: 1in;
        border-top: 5px solid #c15555;
        background-color: #8a2d2d;
    }

    .footer-content {
      padding: 0.125in;
      text-align: center;
      color: #f9fdff;
    }
</style>

// sweng/app/search/page.tsx
"use client"
import { supabase } from "@/db/supa";
import { useRouter } from "next/navigation";    
import Link from "next/link";            

export default function SearchPage() {
  
    const router = useRouter();

    const goHome = () => {
        router.push('/'); 
    };


    return (

        <main className = "flex flex-col min-h-screen bg-[#f9fdff] text-black">

            {/* Header */}
            <div className = "h-[0.75in] border-b-[5px] border-b-[#c15555]">

                <div className = "p-[0.125in] gap-[0.25in] flex flex-row items-center">

                    <img 
                        className = "h-[0.5in]" 
                        src = "/images/logo.png" 
                    />

                    <div className = "text-[30px] text-[#8a2d2d] hover:underline">
                        <h1>Red Bank Foundation</h1>
                    </div>

                </div>

            </div>

            {/* Main Content */}
            <div className = "h-[80%] bg-[#c15555] flex flex-row">

                {/* Left Panel */}
                <div className = "h-full w-[1.3in] bg-[#c15555] flex flex-col pt-[0.5in] gap-[0.25] items-center">

                    {/* Buttons */}
                    <div className = "flex flex-col gap-6 mt-8">

                        {/* Scanner Button */}
                        <Link
                            href = "/scanner"
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >
                            <img src = "/images/scanner.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform"/>

                            <p className = "mt-2 text-sm font-bold text-black-700">Scan QR</p>

                        </Link>

                        {/* Events Button */}
                        <Link 
                            href = "/events" 
                            className = "flex flex-col items-center justify-center p-3 rounded-xl hover:bg-gray-200 transition-all cursor-pointer group w-[100px] mx-auto"
                        >

                            <img src = "/images/planner.png" className = "w-20 h-20 object-contain group-hover:-translate-y-1 transition-transform" />
                            
                            <p className = "mt-2 text-sm font-bold text-black-700">Events</p>

                        </Link>

                    </div>

                </div>

                {/* Main Panel */}
                <div className = "h-full w-[15in] bg-[#f9fdff] p-[0.5in] flex flex-col gap-[0.5in]">

                    <h1 className = "inline bg-[#c15555] text-[56px] text-[#f9fdff] p-[0.25in]">Donor Search</h1>

                    <div className = "flex flex-col gap-[0.5in]">

                        <div className = "flex flex-row gap-[0.5in]">

                            <div className = "relative w-[5in] ">

                                <img className = "absolute h-[0.25in] left-[0.125in] top-[7.5px]" src = "/images/search.png" />

                                <input type = "text" className = "w-[5in] text-[30px] pl-[0.5in] border-2 border-gray-300" placeholder="Input donor name"/>
                            </div>

                            <button className = "w-[1in] bg-[#8a2d2d] text-[#f9fdff] p-[5px] rounded-[10px] text-center cursor-pointer hover:underline">Search</button>

                        </div>

                        <div className = "flex flex-col gap-[15px]">

                            <div className = "flex flex-row justify-between h-[1.5in]">

                                <div className = "h-[1.25in] w-[4.5in] bg-[#c15555] rounded-[20px] flex flex-row gap-[0.25in] transition-transform duration-200 hover:scale-[1.0625]" id="donor">

                                    <div className = "h-[1in] pl-[0.125in] pt-[0.125in] flex">
                                        <img src = "/images/user.png"/>
                                    </div>

                                    <div className="flex flex-col justify-center gap-[7.5px]">
                                        <h3 className = "font-bold text-[#f9fdff] text-[28px]">John Doe</h3>
                                        <p className = "text-[#f9fdff] text-[21px]">john_doe@gmail.com</p>
                                    </div>
                                </div>

                                <div className="h-[1.25in] w-[4.5in] bg-[#c15555] rounded-[20px] flex flex-row gap-[0.25in] transition-transform duration-200 hover:scale-[1.0625]">
                                    
                                    <div className="h-[1in] pl-[0.125in] pt-[0.125in] flex">
                                        <img src="/images/user.png"/>
                                    </div>

                                    <div className="flex flex-col justify-center gap-[7.5px]">
                                        <h3 className = "font-bold text-[#f9fdff] text-[28px]">Janet Doe</h3>
                                        <p className = "text-[#f9fdff] text-[21px]">janet_doe@gmail.com</p>
                                    </div>
                                </div>

                                <div className="h-[1.25in] w-[4.5in] bg-[#c15555] rounded-[20px] flex flex-row gap-[0.25in] transition-transform duration-200 hover:scale-[1.0625]">
                                    
                                    <div className="h-[1in] pl-[0.125in] pt-[0.125in] flex">
                                        <img src="/images/user.png"/>
                                    </div>

                                    <div className="flex flex-col justify-center gap-[7.5px]">
                                        <h3 className = "font-bold text-[#f9fdff] text-[28px]">Jeanne Doe</h3>
                                        <p className = "text-[#f9fdff] text-[21px]">jeanne_doe@gmail.com</p>
                                    </div>
                                </div>
                            </div>

                            <div className = "flex flex-row justify-between h-[1.5in]">

                                <div className = "h-[1.25in] w-[4.5in] bg-[#c15555] rounded-[20px] flex flex-row gap-[0.25in] transition-transform duration-200 hover:scale-[1.0625]">
                                    <div className = "h-[1in] pl-[0.125in] pt-[0.125in] flex">
                                        <img src = "/images/user.png"/>
                                    </div>

                                    <div className = "flex flex-col justify-center gap-[7.5px]">
                                        <h3 className = "font-bold text-[#f9fdff] text-[28px]">Julian Doe</h3>
                                        <p className = "text-[#f9fdff] text-[21px]">julian_doe@gmail.com</p>
                                    </div>
                                </div>

                                <div className = "h-[1.25in] w-[4.5in] bg-[#c15555] rounded-[20px] flex flex-row gap-[0.25in] transition-transform duration-200 hover:scale-[1.0625]">

                                    <div className = "h-[1in] pl-[0.125in] pt-[0.125in] flex">
                                        <img src = "/images/user.png"/>
                                    </div>

                                    <div className = "flex flex-col justify-center gap-[7.5px]">
                                        <h3 className = "font-bold text-[#f9fdff] text-[28px]">Jonah Doe</h3>
                                        <p className = "text-[#f9fdff] text-[21px]">jonah_doe@gmail.com</p>
                                    </div>
                                </div>

                                <div className = "h-[1.25in] w-[4.5in] bg-[#c15555] rounded-[20px] flex flex-row gap-[0.25in] transition-transform duration-200 hover:scale-[1.0625]">
                                    <div className="h-[1in] pl-[0.125in] pt-[0.125in] flex">
                                        <img src="../images/user.png"/>
                                    </div>

                                    <div className="flex flex-col justify-center gap-[7.5px]">
                                        <h3 className = "font-bold text-[#f9fdff] text-[28px]">Janice Doe</h3>
                                        <p className = "text-[#f9fdff] text-[21px]">janice_doe@gmail.com</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>

                <div className = "flex-1 bg-[#c15555]"></div>

            </div>

            <div className = "border-t-[5px] border-[#c15555] bg-[#8a2d2d] flex-1">

                <div className = "p-[0.125in] items-center text-[#f9fdff]">
                
                </div>
            </div>

        </main>

    );
}
